# File Tree
[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
  let NEADTreeShowHidden=1
  nnoremap <silent><C-a> :NERDTreeFind<CR>:vertical res 30<CR>
'''

# navigation bar
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = '''
  let g:airline_theme = 'molokai' 
'''

# git diff
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set signcolumn=yes
  let g:gitgutter_async = 1
  highlight GitGutterAdd ctermfg=green
  highlight GitGutterChange ctermfg=yellow
  highlight GitGutterDelete ctermfg=red
  highlight GitGutterChangeDelete ctermfg=yellow
'''

# comment out
[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
  vnoremap ? :'<,'>TComment<CR>
'''

# bracket syntax
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
  let g:rainbow_active = 1
'''

# file icons
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# file search
[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  nnoremap <C-q> :Rg<Space>
  nnoremap <C-p> :GFiles<CR>
  nnoremap <C-h> :History<CR>
'''

# LSP (Language Server Protocol)
[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
build = 'git checkout release'

# Insert or delete brackets, parens, quotes in pair.
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# bracket replace
[[plugins]]
repo = 'tpope/vim-surround'

# color scheme
[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = '''
  let g:tokyonight_style = "night"
  colorscheme tokyonight
'''
